dataset_path: "/home/pervinco/Datasets/pytorch-mnist"
save_path: "./runs"

model: "CNN_V4"
weight_init: True

num_workers: 4
epochs: 1000
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.000001
drop_prob: 0.25

lr_patience: 5
lr_factor: 0.1
early_stop_patience: 10
